name: "Code_M"

on:
  push:
    branches: [ "main", "paths" ]
  pull_request:
    branches: [ "main", "paths" ]
  schedule:
    - cron: '20 19 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    timeout-minutes: ${{ matrix.language == 'swift' && 120 || 360 }}
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]

    steps:
    - name: Check if docs directory modified
      run: |
        if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *"docs/"* ]]; then
          echo "Skipping analysis as only docs directory modified"
          exit 0
        fi

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}"
