name: "Code_M"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 19 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    timeout-minutes: ${{ matrix.language == 'swift' && 120 || 360 }}
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate git diff

    - name: Set docs modified output
      id: skip_analysis
      run: |
        if git diff --quiet HEAD^ HEAD -- docs; then
          echo "::set-output name=docs_modified::false"
        else
          echo "::set-output name=docs_modified::true"
        fi

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      if: steps.skip_analysis.outputs.docs_modified == 'true'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}"
